'use client';

import { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useForm } from 'react-hook-form';
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Clock3, Eye, FilePenLine, Loader2, Plus, Trash2, UsersRound, XCircle } from 'lucide-react';
import { apiError } from '@/lib/api';
import { date, employmentLabels, levelLabels, location, statusLabels } from '@/lib/format';
import { mutations, useApiMutation, useCompanyDashboard, useCompanyJobs, useCompanyProfile, useJob, useJobApplications } from '@/lib/queries';
import type { ApplicationStatus, CompanyProfile, EmploymentType, ExperienceLevel, JobPayload } from '@/lib/types';
import { AppPage, EmptyState, ErrorState, LoadingCards, PageHeader, StatCard, StatusBadge } from '@/components/app/common';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import { toast } from '@/components/ui/toast';

export function CompanyDashboardPage() {
  const query = useCompanyDashboard(); const jobs = useCompanyJobs();
  if (query.isLoading) return <AppPage><LoadingCards /></AppPage>;
  if (query.isError || !query.data) return <AppPage><ErrorState retry={() => query.refetch()} /></AppPage>;
  const d = query.data; const chart = [{ name: 'Em análise', value: d.underReview }, { name: 'Entrevistas', value: d.interviews }, { name: 'Aprovadas', value: d.accepted }];
  return <AppPage><PageHeader eyebrow="Área da empresa" title="Talentos e vagas, em perspectiva" description="Acompanhe o desempenho das oportunidades e avance candidatos com agilidade." action={<Button nativeButton={false} render={<Link to="/company/jobs/new" />}><Plus /> Publicar vaga</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Vagas abertas" value={d.openJobs} icon={BriefcaseBusiness} /><StatCard label="Candidaturas" value={d.totalApplications} icon={UsersRound} /><StatCard label="Em análise" value={d.underReview} icon={Clock3} tone="amber" /><StatCard label="Contratações" value={d.accepted} icon={CheckCircle2} tone="green" /></div><div className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Vagas recentes</CardTitle><Button variant="ghost" size="sm" nativeButton={false} render={<Link to="/company/jobs" />}>Gerenciar</Button></CardHeader><CardContent>{jobs.isLoading ? <LoadingCards count={2} /> : jobs.data?.length ? <div className="divide-y">{jobs.data.slice(0, 5).map(job => <div key={job.id} className="flex items-center gap-4 py-4"><span className="grid size-10 place-items-center rounded-lg bg-secondary text-primary"><BriefcaseBusiness className="size-4" /></span><div className="min-w-0 flex-1"><Link to={`/company/jobs/${job.id}/applications`} className="font-medium hover:text-primary">{job.title}</Link><p className="text-sm text-muted-foreground">{location(job)} · {date(job.createdAt)}</p></div><Badge variant={job.status === 'OPEN' ? 'default' : 'secondary'}>{job.status === 'OPEN' ? 'Aberta' : 'Encerrada'}</Badge></div>)}</div> : <EmptyState title="Nenhuma vaga publicada" description="Publique sua primeira oportunidade para começar a receber candidatos." actionLabel="Publicar vaga" actionTo="/company/jobs/new" />}</CardContent></Card><Card><CardHeader><CardTitle>Funil atual</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} layout="vertical" margin={{ left: 8 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="name" width={86} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="value" fill="#0f766e" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card></div></AppPage>;
}

export function CompanyJobsPage() {
  const query = useCompanyJobs(); const close = useApiMutation((id: number) => mutations.closeJob(id), [['company-jobs'], ['company-dashboard']]); const remove = useApiMutation((id: number) => mutations.deleteJob(id), [['company-jobs'], ['company-dashboard']]);
  return <AppPage><PageHeader eyebrow="Gestão de oportunidades" title="Minhas vagas" description="Edite, encerre e acompanhe as candidaturas de cada publicação." action={<Button nativeButton={false} render={<Link to="/company/jobs/new" />}><Plus /> Nova vaga</Button>} />{query.isLoading ? <LoadingCards /> : query.isError ? <ErrorState retry={() => query.refetch()} /> : query.data?.length ? <Card><Table><TableHeader><TableRow><TableHead>Vaga</TableHead><TableHead className="hidden md:table-cell">Local</TableHead><TableHead>Status</TableHead><TableHead className="hidden lg:table-cell">Publicada</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{query.data.map(job => <TableRow key={job.id}><TableCell><div className="font-medium">{job.title}</div><div className="text-xs text-muted-foreground">{employmentLabels[job.employmentType]} · {levelLabels[job.experienceLevel]}</div></TableCell><TableCell className="hidden md:table-cell">{location(job)}</TableCell><TableCell><Badge variant={job.status === 'OPEN' ? 'default' : 'secondary'}>{job.status === 'OPEN' ? 'Aberta' : 'Encerrada'}</Badge></TableCell><TableCell className="hidden lg:table-cell">{date(job.createdAt)}</TableCell><TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" nativeButton={false} render={<Link to={`/company/jobs/${job.id}/applications`} />} aria-label="Ver candidaturas"><Eye /></Button>{job.status === 'OPEN' && <><Button variant="ghost" size="icon" nativeButton={false} render={<Link to={`/company/jobs/${job.id}/edit`} />} aria-label="Editar"><FilePenLine /></Button><Button variant="ghost" size="icon" onClick={() => close.mutate(job.id)} aria-label="Encerrar"><XCircle /></Button></>}<Button variant="ghost" size="icon" onClick={() => confirm('Excluir esta vaga permanentemente?') && remove.mutate(job.id)} aria-label="Excluir"><Trash2 className="text-destructive" /></Button></div></TableCell></TableRow>)}</TableBody></Table></Card> : <EmptyState title="Nenhuma vaga publicada" description="Crie sua primeira oportunidade e comece a montar seu time." actionLabel="Publicar vaga" actionTo="/company/jobs/new" />}</AppPage>;
}

type JobFormData = Omit<JobPayload, 'skills' | 'expiresAt' | 'salaryMin' | 'salaryMax'> & { skillsText: string; expiresAt: string; salaryMin?: string; salaryMax?: string };
export function JobFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const job = useJob(id); const form = useForm<JobFormData>({ defaultValues: { title: '', description: '', city: '', state: '', country: 'Brasil', remote: false, employmentType: 'FULL_TIME', experienceLevel: 'MID_LEVEL', salaryMin: '', salaryMax: '', expiresAt: '', skillsText: '' } });
  useEffect(() => { if (job.data && editing) form.reset({ title: job.data.title, description: job.data.description, city: job.data.city ?? '', state: job.data.state ?? '', country: job.data.country ?? 'Brasil', remote: job.data.remote, employmentType: job.data.employmentType, experienceLevel: job.data.experienceLevel, salaryMin: job.data.salaryMin?.toString() ?? '', salaryMax: job.data.salaryMax?.toString() ?? '', expiresAt: job.data.expiresAt.slice(0, 16), skillsText: job.data.skills.join(', ') }); }, [job.data, editing, form]);
  const save = useApiMutation((payload: JobPayload) => editing ? mutations.updateJob(Number(id), payload) : mutations.createJob(payload), [['company-jobs'], ['company-dashboard']]);
  const submit = form.handleSubmit(data => { const payload: JobPayload = { ...data, salaryMin: data.salaryMin ? Number(data.salaryMin) : undefined, salaryMax: data.salaryMax ? Number(data.salaryMax) : undefined, expiresAt: new Date(data.expiresAt).toISOString(), skills: data.skillsText.split(',').map(x => x.trim()).filter(Boolean) }; save.mutate(payload, { onSuccess: () => { toast.add({ title: editing ? 'Vaga atualizada' : 'Vaga publicada', type: 'success' }); navigate('/company/jobs'); } }); });
  if (editing && job.isLoading) return <AppPage><LoadingCards /></AppPage>;
  return <AppPage><Button variant="ghost" className="mb-5 -ml-2" onClick={() => navigate('/company/jobs')}><ArrowLeft /> Voltar</Button><PageHeader eyebrow={editing ? 'Edição' : 'Nova oportunidade'} title={editing ? 'Editar vaga' : 'Publicar uma vaga'} description="Descreva com clareza o desafio, o contexto e as competências realmente necessárias." /><form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle>Detalhes da oportunidade</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Título da vaga" className="sm:col-span-2"><Input required maxLength={180} {...form.register('title')} /></Field><Field label="Descrição" className="sm:col-span-2"><Textarea required rows={10} maxLength={10000} {...form.register('description')} /></Field><Field label="Tipo de contrato"><select {...form.register('employmentType')} className="h-10 w-full rounded-lg border bg-background px-3 text-sm">{(['FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP'] as EmploymentType[]).map(type => <option key={type} value={type}>{employmentLabels[type]}</option>)}</select></Field><Field label="Senioridade"><select {...form.register('experienceLevel')} className="h-10 w-full rounded-lg border bg-background px-3 text-sm">{(['INTERN','JUNIOR','MID_LEVEL','SENIOR'] as ExperienceLevel[]).map(level => <option key={level} value={level}>{levelLabels[level]}</option>)}</select></Field><Field label="Cidade"><Input {...form.register('city')} /></Field><Field label="Estado"><Input {...form.register('state')} /></Field><Field label="País"><Input {...form.register('country')} /></Field><Field label="Expira em"><Input required type="datetime-local" {...form.register('expiresAt')} /></Field><Field label="Salário mínimo"><Input type="number" min="0" step="100" {...form.register('salaryMin')} /></Field><Field label="Salário máximo"><Input type="number" min="0" step="100" {...form.register('salaryMax')} /></Field><Field label="Competências" className="sm:col-span-2"><Input {...form.register('skillsText')} placeholder="Java, Spring Boot, PostgreSQL" /><p className="mt-1 text-xs text-muted-foreground">Separe por vírgulas.</p></Field><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" {...form.register('remote')} className="size-4 accent-primary" /> Esta vaga aceita trabalho remoto</label></CardContent></Card><aside><Card><CardHeader><CardTitle>Publicação</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">Revise os dados antes de publicar. Você poderá editar enquanto a vaga estiver aberta.</p>{save.isError && <p className="mt-4 text-sm text-destructive">{apiError(save.error)}</p>}<Button type="submit" size="lg" className="mt-6 w-full" disabled={save.isPending}>{save.isPending && <Loader2 className="animate-spin" />}{editing ? 'Salvar alterações' : 'Publicar vaga'}</Button></CardContent></Card></aside></form></AppPage>;
}

export function JobApplicationsPage() {
  const { id } = useParams(); const job = useJob(id); const query = useJobApplications(id); const update = useApiMutation(({ appId, status }: { appId: number; status: ApplicationStatus }) => mutations.updateStatus(appId, status), [['job-applications', id!], ['company-dashboard']]);
  return <AppPage><Button variant="ghost" className="mb-5 -ml-2" nativeButton={false} render={<Link to="/company/jobs" />}><ArrowLeft /> Voltar</Button><PageHeader eyebrow="Seleção" title={job.data?.title ?? 'Candidaturas'} description="Avalie competências e atualize o andamento de cada candidato." />{query.isLoading ? <LoadingCards /> : query.isError ? <ErrorState retry={() => query.refetch()} /> : query.data?.length ? <div className="grid gap-4">{query.data.map(app => <Card key={app.id}><CardContent className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-primary/10 font-semibold text-primary">{app.candidate.name[0]}</span><div><p className="font-semibold">{app.candidate.name}</p><p className="text-sm text-muted-foreground">{app.candidate.headline || levelLabels[app.candidate.experienceLevel ?? 'JUNIOR']}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{app.candidate.skills.map(skill => <Badge key={skill} variant="secondary">{skill}</Badge>)}</div>{app.coverLetter && <p className="mt-4 max-w-3xl rounded-lg bg-secondary/50 p-4 text-sm leading-6 text-muted-foreground">{app.coverLetter}</p>}</div><div className="flex min-w-48 flex-col items-end gap-3"><StatusBadge status={app.status} /><select value={app.status} onChange={e => update.mutate({ appId: app.id, status: e.target.value as ApplicationStatus })} className="h-9 rounded-lg border bg-background px-3 text-sm" aria-label={`Atualizar status de ${app.candidate.name}`}>{(['APPLIED','UNDER_REVIEW','INTERVIEW','REJECTED','ACCEPTED'] as ApplicationStatus[]).map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select><span className="text-xs text-muted-foreground">Recebida em {date(app.appliedAt)}</span></div></div></CardContent></Card>)}</div> : <EmptyState title="Nenhuma candidatura recebida" description="Os candidatos desta vaga aparecerão aqui." />}</AppPage>;
}

type CompanyForm = Pick<CompanyProfile, 'companyName' | 'description' | 'website' | 'city' | 'state' | 'country'>;
export function CompanyProfilePage() {
  const query = useCompanyProfile(); const form = useForm<CompanyForm>(); useEffect(() => { if (query.data) form.reset({ companyName: query.data.companyName, description: query.data.description ?? '', website: query.data.website ?? '', city: query.data.city ?? '', state: query.data.state ?? '', country: query.data.country ?? 'Brasil' }); }, [query.data, form]);
  const save = useApiMutation((data: CompanyForm) => mutations.updateCompany(data), [['company-profile']]);
  if (query.isLoading) return <AppPage><LoadingCards /></AppPage>;
  return <AppPage><PageHeader eyebrow="Presença da empresa" title="Perfil da empresa" description="Apresente sua cultura e ajude candidatos a entender onde eles podem gerar impacto." /><form onSubmit={form.handleSubmit(data => save.mutate(data, { onSuccess: () => toast.add({ title: 'Perfil da empresa atualizado', type: 'success' }) }))} className="grid gap-6 lg:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle>Informações públicas</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Nome da empresa" className="sm:col-span-2"><Input required {...form.register('companyName')} /></Field><Field label="Sobre a empresa" className="sm:col-span-2"><Textarea rows={8} {...form.register('description')} /></Field><Field label="Website" className="sm:col-span-2"><Input type="url" {...form.register('website')} placeholder="https://…" /></Field><Field label="Cidade"><Input {...form.register('city')} /></Field><Field label="Estado"><Input {...form.register('state')} /></Field><Field label="País"><Input {...form.register('country')} /></Field></CardContent></Card><aside><Card><CardHeader><CardTitle>Responsável pela conta</CardTitle></CardHeader><CardContent className="text-sm"><p className="font-medium">{query.data?.ownerName}</p><p className="mt-1 text-muted-foreground">{query.data?.email}</p><Button type="submit" size="lg" className="mt-6 w-full" disabled={save.isPending}>{save.isPending && <Loader2 className="animate-spin" />} Salvar perfil</Button>{save.isError && <p className="mt-3 text-destructive">{apiError(save.error)}</p>}</CardContent></Card></aside></form></AppPage>;
}

function Field({ label, className, children }: { label: string; className?: string; children: React.ReactNode }) { return <div className={className}><Label className="mb-2 block">{label}</Label>{children}</div>; }
